### ISSUE TITLE
Line 23 error

### ISSUE THREAD

**Issue by ghost** [stefanfortuin/4anime.to-scraper#2]
![Screenshot from 2019-08-05 16-10-54](https://user-images.githubusercontent.com/8528269/62448963-a22a3600-b79b-11e9-92eb-76cf1aa3f2b5.png)

**Comment by stefanfortuin** [comment]
What version of python are you using?
It could be that the version you are using does not support f-strings
[F-Strings](https://www.python.org/dev/peps/pep-0498/)

Sorry for the late reply
